---

#
# AtoM maintenance handlers
# (Ubuntu only for now, could be expanded for other OS options)
#

# Ubuntu 14.04 defaults to php5-fpm and Ubuntu 16.04 to php7-fpm
- include: ubuntu-14.04.yml
  when: "ansible_distribution_version | version_compare('14.04', '==')"

- include: ubuntu-16.04.yml
  when: "ansible_distribution_version | version_compare('16.04', '==')"

- name: "Restart smbd"
  service:
    name: "smbd"
    state: "restarted"

- name: "Restart nmbd"
  service:
    name: "nmbd"
    state: "restarted"

#
# Symfony tasks
#
- name: "Clear sf_cache"
  shell: "php symfony cc"
  args:
    chdir: "{{ atom_path }}"
  become_user: "{{ atom_user }}"
